name: cookbook
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:

  animated_text_kit: ^4.2.2
  bottom_navy_bar: ^6.0.0
  cloud_firestore: ^3.5.1
  cupertino_icons: ^1.0.2
  day_night_switcher: ^0.2.0+1
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  firebase_database: ^9.1.7
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_picker: ^0.8.6
  nanoid: ^1.0.0
  provider: ^6.0.5
  

dev_dependencies:
  build_runner: ^2.3.3
  flutter_native_splash: ^2.2.11
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  

flutter_native_splash: 
  background_image: assets/background_image.png
  

flutter:

  uses-material-design: true

  assets:
    - assets/background_login.png
    - assets/recipe_example.jpg
    - assets/meal_loading.jpg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
